server:
  port: 8081
spring:

  datasource:
    url: jdbc:mysql://localhost/tmchecking
    username: admin
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver
#  data: classpath:/data.sql
#  initialization-mode: always
  jpa:

    show-sql: true
    hibernate:
       naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
       ddl-auto: update
    properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

